package com.ptutor.backend.entity.enums;

public enum NotificationEventType {
    PAYMENT_SUCCEEDED,
    PAYMENT_INSTALLMENT_DUE,
    TUTOR_REQUEST_RECEIVED,
    TUTOR_REQUEST_ACCEPTED,
    TUTOR_REQUEST_REJECTED,
    STUDENT_REQUEST_RECEIVED,
    STUDENT_REQUEST_ACCEPTED,
    STUDENT_REQUEST_REJECTED,
    CONTRACT_SIGNATURE_REQUIRED,
    CONTRACT_SIGNED,
    CONTRACT_REJECTED,
    CONTRACT_CANCELLED,
    CONTRACT_RENEWAL_PROPOSED,
    CERTIFICATE_APPROVED,
    CERTIFICATE_REJECTED,
    TEACHING_REQUEST_APPROVED,
    TEACHING_REQUEST_REJECTED,
    COMPLAINT_EVIDENCE_REQUESTED,
    COMPLAINT_RESOLVED,
    COMPLAINT_REJECTED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_REACTIVATED
}
