spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/ptutor
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true